# Generated by Django 5.2 on 2025-06-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип опции')),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='menu.optiontype', verbose_name='Тип опции')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.optiontype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_types', to='menu.product')),
            ],
            options={
                'unique_together': {('product', 'option_type')},
            },
        ),
    ]
