# Generated by Django 5.2 on 2025-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_optiontype_optionvalue_productoptiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
