# Generated by Django 5.2 on 2025-06-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_product_has_options_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optiontype',
            options={'verbose_name': 'Тип опции', 'verbose_name_plural': 'Тип опции'},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'verbose_name': 'Значение опции', 'verbose_name_plural': 'Значение опции'},
        ),
        migrations.AlterModelOptions(
            name='productoptiontype',
            options={'verbose_name': 'Опции конкеретно к продутку', 'verbose_name_plural': 'Опции конкеретно к продутку'},
        ),
    ]
