# Generated by Django 5.2 on 2025-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_optiontype_options_alter_optionvalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_percent',
            field=models.FloatField(default=5.0, verbose_name='Проценты для бонуса'),
        ),
    ]
