# Generated by Django 5.2 on 2025-12-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_product_bonus_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoptiontype',
            options={'verbose_name': 'Опции конкретно к продукту', 'verbose_name_plural': 'Опции конкретно к продукту'},
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='additional_cost',
            field=models.PositiveIntegerField(default=0, help_text='Сколько добавляется к базовой цене товара при выборе этой опции', verbose_name='Дополнительная стоимость'),
        ),
        migrations.AlterField(
            model_name='productoptiontype',
            name='option_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='menu.optiontype'),
        ),
    ]
