# Generated by Django 5.2 on 2026-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_productoptiontype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="title_ky",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="category",
            name="title_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ky",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ky",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="title_ky",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="title_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
    ]
