# Generated by Django 5.2 on 2026-08-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_add_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoptiontype",
            name="allow_multiple",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, пользователь может выбрать несколько значений этой опции",
                verbose_name="Можно выбрать несколько",
            ),
        ),
    ]
