# Generated by Django 5.2 on 2026-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="content_ky",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AddField(
            model_name="news",
            name="short_description_ky",
            field=models.TextField(null=True, verbose_name="Краткое описание"),
        ),
        migrations.AddField(
            model_name="news",
            name="short_description_ru",
            field=models.TextField(null=True, verbose_name="Краткое описание"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
    ]
