# Generated by Django 5.2 on 2025-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coffee_cups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
