# Generated by Django 5.2 on 2026-03-25 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cafe_membership_and_order_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'verbose_name': 'Кафе', 'verbose_name_plural': 'Кафе'},
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddIndex(
            model_name='cafemembership',
            index=models.Index(fields=['cafe', 'role'], name='order_cafem_cafe_id_063bab_idx'),
        ),
    ]
