# Generated by Django 5.2 on 2026-05-09 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_cafe_options_alter_cafe_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="order_user_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["cafe"], name="order_cafe_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["courier"], name="order_courier_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "cafe"], name="order_status_cafe_idx"),
        ),
    ]
