# Generated by Django 5.2 on 2026-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_add_order_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Ваш заказ принят"),
                    ("ready", "Заказ готов"),
                    ("on_the_way", "Курьер в пути"),
                    ("delivered", "Заказ доставлен"),
                    ("cancelled", "Заказ отменён"),
                ],
                default="accepted",
                max_length=20,
            ),
        ),
    ]
