# Generated by Django 5.2 on 2026-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_add_cancelled_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bonus_spent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
